paths:
  train_CBCT: ../training_data/CBCT
  train_CT: ../training_data/CT

model:
  latent_dim: 4
  image_size: 256
  num_heads: 8

train:
  batch_size: 4
  epochs: 5000
  initial_epochs: 20
  subset_size: 500
  learning_rate: 1e-4
  fine_tune_lr: 1e-5
  min_learning_rate: 1e-6
  min_fine_tune_lr: 1e-7
  weight_decay: 1e-5
  fine_tune_weight_decay: 1e-6
  scheduler_patience: 10
  early_stopping_patience: 50
  num_workers: 8

diffusion:
  timesteps: 1000