paths:
  train_CBCT: ../training_data/CBCT
  train_CT: ../training_data/CT
  save_path: "checkpoints/ssim_kl.pth"

model:
  latent_dim: 4
  image_size: 256
  num_heads: 8

vae:
  beta: 0.000001
  max_beta: 0.000001
  lambda_perceptual: 0.1
  lambda_ssim: 1
  lambda_l2: 0
  lambda_l1: 0

train:
  batch_size: 4
  epochs: 2000
  initial_epochs: 20
  subset_size: 500
  learning_rate: 4.5e-6
  fine_tune_lr: 1e-5
  min_learning_rate: 1e-4
  min_fine_tune_lr: 1e-6
  weight_decay: 1e-5
  fine_tune_weight_decay: 1e-6
  scheduler_patience: 20
  early_stopping_patience: 50
  num_workers: 8

diffusion:
  timesteps: 1000